### ISSUE TITLE
no such table: auth_user

### ISSUE THREAD

**Issue by ams-123** [joplin-vieweb/joplin-vieweb#41]
Hi,

Joplin web is up and running and have connected a custom domain. When I log into Django administration, I see Server Error (500). In the logs:

HTTP b'POST' request for ['127.0.0.1', 50508]
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_user

I've tried a clean install, deleted directories, etc, but cannot get past this error.

**Comment by gri38** [comment]
Hi
This quick post just to say I've seen your issue report... unfortunatly I'm on a business trip the whole week, you'll have to wait.

In the meantime, could you try to reinstall from scratch, and when you do you docker-compose up, don't pass the -d option, so you'll see all the logs of all the containers.
The error you reported makes me think the admin app is not wel installed, or the volume for the sqlite database is not created, or something around that.
Could you try, and paste the logs here.

Thanks

**Comment by mcrainydrop** [comment]
Hello,
I know, this ticket is rather old, but I've encountered the same issue also with the newest version.

I did a fresh installation using the docker image and just configured the environment variables for the ORIGINS. Beside that, all is directly plain from the documentation. 
After starting the container and going to the admin url, I've entered the default admin credentials and see the following error in the container logs:


~~~
Oct 17 17:26:29 616-joplin-web HTTP b'POST' request for ['127.0.0.1', 47208]
Oct 17 17:26:29 616-joplin-web Internal Server Error: /admin/login/
Oct 17 17:26:29 616-joplin-web Traceback (most recent call last):
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
Oct 17 17:26:29 616-joplin-web     return self.cursor.execute(sql, params)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
Oct 17 17:26:29 616-joplin-web     return super().execute(query, params)
Oct 17 17:26:29 616-joplin-web sqlite3.OperationalError: no such table: auth_user
Oct 17 17:26:29 616-joplin-web
Oct 17 17:26:29 616-joplin-web The above exception was the direct cause of the following exception:
Oct 17 17:26:29 616-joplin-web
Oct 17 17:26:29 616-joplin-web Traceback (most recent call last):
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 534, in thread_handler
Oct 17 17:26:29 616-joplin-web     raise exc_info[1]
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
Oct 17 17:26:29 616-joplin-web     response = await get_response(request)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
Oct 17 17:26:29 616-joplin-web     response = await wrapped_callback(
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 479, in __call__
Oct 17 17:26:29 616-joplin-web     ret: _R = await loop.run_in_executor(
Oct 17 17:26:29 616-joplin-web   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Oct 17 17:26:29 616-joplin-web     result = self.fn(*self.args, **self.kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 538, in thread_handler
Oct 17 17:26:29 616-joplin-web     return func(*args, **kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
Oct 17 17:26:29 616-joplin-web     return bound_method(*args, **kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
Oct 17 17:26:29 616-joplin-web     response = view_func(request, *args, **kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 441, in login
Oct 17 17:26:29 616-joplin-web     return LoginView.as_view(**defaults)(request)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
Oct 17 17:26:29 616-joplin-web     return self.dispatch(request, *args, **kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
Oct 17 17:26:29 616-joplin-web     return bound_method(*args, **kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
Oct 17 17:26:29 616-joplin-web     return view(request, *args, **kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
Oct 17 17:26:29 616-joplin-web     return bound_method(*args, **kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
Oct 17 17:26:29 616-joplin-web     response = view_func(request, *args, **kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
Oct 17 17:26:29 616-joplin-web     return bound_method(*args, **kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
Oct 17 17:26:29 616-joplin-web     response = view_func(request, *args, **kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/contrib/auth/views.py", line 90, in dispatch
Oct 17 17:26:29 616-joplin-web     return super().dispatch(request, *args, **kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
Oct 17 17:26:29 616-joplin-web     return handler(request, *args, **kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/views/generic/edit.py", line 152, in post
Oct 17 17:26:29 616-joplin-web     if form.is_valid():
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/forms/forms.py", line 201, in is_valid
Oct 17 17:26:29 616-joplin-web     return self.is_bound and not self.errors
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/forms/forms.py", line 196, in errors
Oct 17 17:26:29 616-joplin-web     self.full_clean()
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/forms/forms.py", line 434, in full_clean
Oct 17 17:26:29 616-joplin-web     self._clean_form()
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/forms/forms.py", line 455, in _clean_form
Oct 17 17:26:29 616-joplin-web     cleaned_data = self.clean()
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/contrib/auth/forms.py", line 242, in clean
Oct 17 17:26:29 616-joplin-web     self.user_cache = authenticate(
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
Oct 17 17:26:29 616-joplin-web     return func(*func_args, **func_kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 77, in authenticate
Oct 17 17:26:29 616-joplin-web     user = backend.authenticate(request, **credentials)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/contrib/auth/backends.py", line 46, in authenticate
Oct 17 17:26:29 616-joplin-web     user = UserModel._default_manager.get_by_natural_key(username)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 54, in get_by_natural_key
Oct 17 17:26:29 616-joplin-web     return self.get(**{self.model.USERNAME_FIELD: username})
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
Oct 17 17:26:29 616-joplin-web     return getattr(self.get_queryset(), name)(*args, **kwargs)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 633, in get
Oct 17 17:26:29 616-joplin-web     num = len(clone)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 380, in __len__
Oct 17 17:26:29 616-joplin-web     self._fetch_all()
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 1881, in _fetch_all
Oct 17 17:26:29 616-joplin-web     self._result_cache = list(self._iterable_class(self))
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 91, in __iter__
Oct 17 17:26:29 616-joplin-web     results = compiler.execute_sql(
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
Oct 17 17:26:29 616-joplin-web     cursor.execute(sql, params)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
Oct 17 17:26:29 616-joplin-web     return self._execute_with_wrappers(
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
Oct 17 17:26:29 616-joplin-web     return executor(sql, params, many, context)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
Oct 17 17:26:29 616-joplin-web     return self.cursor.execute(sql, params)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
Oct 17 17:26:29 616-joplin-web     raise dj_exc_value.with_traceback(traceback) from exc_value
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
Oct 17 17:26:29 616-joplin-web     return self.cursor.execute(sql, params)
Oct 17 17:26:29 616-joplin-web   File "/root/.local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
Oct 17 17:26:29 616-joplin-web     return super().execute(query, params)
Oct 17 17:26:29 616-joplin-web django.db.utils.OperationalError: no such table: auth_user
Oct 17 17:26:29 616-joplin-web HTTP 500 response started for ['127.0.0.1', 47208]
~~~

I also had a look in the `database.sqlite` (present in the docker volume and automatically created during first container startup) and indeed, the mentioned table `auth_user` is not present. A lot of other tables seem to be instantiated properly, but this one is missing.

Is there something missing in the compose configuration or is this an error ?

Thanks and kind regards
raindrop

**Comment by gri38** [comment]
Hi @mcrainydrop 
I'll have a look and try to install, lioke you, from scratch.
Right now I don't see why could cause this error... I would need to dive inside again... I've been too long far from that.

I'll have a look as fast as I can.

**Comment by gri38** [comment]
Hello @mcrainydrop and @ams-123 
I've just try to work on that topic, but I cannot reproduce your issue.

What I've done: 
`docker-compose up` in a "fresh install", which means I've deleted joplin and joplin-veweb volumes.

You can delete volumes by docker command, or if your docker-compose is "up", you can do: `docker-compose down -v`  
⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠
⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠
It will delete your volumes, if you have your notes inside, be sure they are safe elsewhere !!!


When docker-compose is up, I can see in the django-joplin-vieweb container logs:
```txt
...

Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK
```

then everything is ok for me: I can login in the admin (http://localhost/admin), create user, login with that user...

Please try again, but before, do [an upgrade of the images](https://github.com/joplin-vieweb/joplin-vieweb/releases/tag/v2.4.3): I've fixed bug #34 , it may change something in your case (or not, but let's work on the last versions):
```bash
sudo docker-compose down
sudo docker-compose pull
sudo docker-compose up -d
```

I'm waiting for your feedback.

**Comment by mcrainydrop** [comment]
Hello, 

first of all, thank you for your time and investigation!

I tried the new container version as you suggested, but the issue was still present.
As you have posted the "correct" logs from your container startup, I had a look at my startup logs and found a discrepancy:
Although the startup was finished successfully with the following content:

```
Nov  2 16:37:32 616-joplin-web Starting server at tcp:port=8001:interface=127.0.0.1
Nov  2 16:37:32 616-joplin-web HTTP/2 support not enabled (install the http2 and tls Twisted extras)
Nov  2 16:37:32 616-joplin-web Configuring endpoint tcp:port=8001:interface=127.0.0.1
Nov  2 16:37:32 616-joplin-web Listening on TCP address 127.0.0.1:8001
```

But before that there were some errors with the CSRF configuration:

```
Nov  2 16:37:28 616-joplin-web SystemCheckError: System check identified some issues:
Nov  2 16:37:28 616-joplin-web ERRORS:
Nov  2 16:37:28 616-joplin-web ?: (4_0.E001) As of Django 4.0, the values in the CSRF_TRUSTED_ORIGINS setting must start with a scheme (usually http:// or https://) but found 127.0.
0.1. See the release notes for details.
```

Due to the fact, that the startup continued and the correct values from my configuration in the compose are printed, I've underestimated this message as real error.
I've specified just 127.0.0.1 (without http) as second allowed value for the ORIGINS variable (I had to specify a second value, because without that, I got an error, that the configuration was invalid).

I don't know, whether this is an Django internal behavior or something in the app, that the bootstrapping just continues successfully although this error (and therefore no database initialization) ?!

But anyway, thank you very much for providing a "startup" help for debugging this issue !

**Comment by gri38** [comment]
Hi @mcrainydrop 

Yes in the ORIGINS variable in the docker-compose file you must specify a scheme (http or https): the one you will use to access your notes.

For instance mine is like that:

```yml
x-common-variables: &common-variables
   ORIGINS: "'https://mydomain.fr'"
```

So you should be able to give only one ORIGIN.

Maybe previously you has the #34 issue that made you "believe" you need 2 origins.

So please try with origins you need, providing scheme.
For instance you may write something like that:
```yml
x-common-variables: &common-variables
   ORIGINS: "'https://yourdomain.com', 'http://localhost:8000'"
```
if you want to access your notes from those urls:
- https://yourdomain.com/joplin
- http://localhost:8000/joplin  (the product listens to port 8000).
Be carreful: the list of origins is between double quotes ("), and each origin is between simple quote(').

Let's try to fix that... then we'll see this issue about no such table....

**Comment by mcrainydrop** [comment]
Indeed, you are right!
It's also working with just one entry in the ORIGINS :-)

I think, I mixed the database initialization error (due to the missing scheme) up with the ORIGINS specification error, or as you said, it was solved due to the other issue.

Anyway, both problems are resolved now and it's working, thank you very much !!
