### ISSUE TITLE
"Error while retrieving notebooks" if delete a notebook with a note insided

### ISSUE THREAD

**Issue by ckholy2** [joplin-vieweb/joplin-vieweb#76]
I found that when I delete a notebook with a note insided, the django-joplin-vieweb will return "Error while retrieving notebooks".  The notebook is actually deleted and sync to joplin server, but django-joplin-vieweb cannot access all notebooks until I restart the joplin-terminal-xapi container.

This problem doesn't exist if I delete the notebook via joplin terminal inside the joplin-terminal-xapi container.

In the joplin-terminal-xapi container, I found below "SQLITE_ERROR".

joplin-vieweb-joplin-terminal-xapi-1
date,stream,content
2024/09/28 19:05:02,stdout,    stderr: 

2024/09/28 19:05:02,stdout,

2024/09/28 19:05:02,stdout,Deleted remote items: 2. Fetched items: 2/2. Completed: 28/09/2024 11:05 (736ms)

2024/09/28 19:05:02,stdout,Downloading resources...

2024/09/28 19:05:02,stdout,Deleted remote items: 1.

2024/09/28 19:05:02,stdout,Starting synchronisation...

2024/09/28 19:05:02,stdout,    stdout: Synchronisation target:  (9)

2024/09/28 19:05:02,stdout,    status: 2024-09-28T11:05:02.875Z

2024/09/28 19:05:02,stdout,Synch finished: return code: 0

2024/09/28 19:00:56,stderr,Node.js v18.19.0

2024/09/28 19:00:56,stderr,

2024/09/28 19:00:56,stderr,}

2024/09/28 19:00:56,stderr,  code: 'SQLITE_ERROR'

2024/09/28 19:00:56,stderr,    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

2024/09/28 19:00:56,stderr,    at rejected (/app/joplin/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:6:65)

2024/09/28 19:00:56,stderr,    at Generator.throw (<anonymous>)

2024/09/28 19:00:56,stderr,    at JoplinDatabase.<anonymous> (/app/joplin/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:135:36)

2024/09/28 19:00:56,stderr,    at JoplinDatabase.sqliteErrorToJsError (/app/joplin/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:34:30)

2024/09/28 19:00:56,stderr,    at DatabaseDriverNode.sqliteErrorToJsError (/app/joplin/lib/node_modules/joplin/node_modules/@joplin/lib/database-driver-node.js:23:18)

2024/09/28 19:00:56,stderr,"Error: Error: SQLITE_ERROR: no such column: undefined: SELECT `id`,`title`,`is_todo`,`todo_completed`,`todo_due`,`parent_id`,`encryption_applied`,`order`,`markup_language`,`is_conflict`,`is_shared`,`share_id`,`updated_time`,`user_updated_time`,`user_created_time` FROM `notes` WHERE is_conflict = 0 AND parent_id = ? AND is_todo = 1 AND (todo_completed <= 0 OR todo_completed IS NULL) ORDER BY `undefined` COLLATE NOCASE ASC: d7d60cd1329e4641a58b88e86ee38f5c
"
2024/09/28 19:00:56,stderr,

2024/09/28 19:00:56,stderr,		               ^

2024/09/28 19:00:56,stderr,		const output = new Error(msg.join(': '));

2024/09/28 19:00:56,stderr,/app/joplin/lib/node_modules/joplin/node_modules/@joplin/lib/database-driver-node.js:23

2024/09/28 19:00:56,stdout,11:00:56: Request: DELETE /folders/0e9b11786892481ab411d769fe95acc7?token=6676cf2c3fab2f7e6ebda5b7afcc0618e5111b9fa67abaa881f7d1448e3ec9986466d325cb26208d364a5a1cb67c90b59f4091fc0816dfc3e656d23298896ae1

2024/09/28 19:00:56,stdout,"11:00:56: Request: GET /notes?fields=id,title,parent_id,is_todo,todo_completed&token=6676cf2c3fab2f7e6ebda5b7afcc0618e5111b9fa67abaa881f7d1448e3ec9986466d325cb26208d364a5a1cb67c90b59f4091fc0816dfc3e656d23298896ae1
"
2024/09/28 19:00:52,stdout,"11:00:52: Request: GET /notes?fields=id,title,parent_id,is_todo,todo_completed&token=6676cf2c3fab2f7e6ebda5b7afcc0618e5111b9fa67abaa881f7d1448e3ec9986466d325cb26208d364a5a1cb67c90b59f4091fc0816dfc3e656d23298896ae1
"
2024/09/28 19:00:50,stdout,"11:00:50: Request: GET /notes?fields=id,title,parent_id,is_todo,todo_completed&token=6676cf2c3fab2f7e6ebda5b7afcc0618e5111b9fa67abaa881f7d1448e3ec9986466d325cb26208d364a5a1cb67c90b59f4091fc0816dfc3e656d23298896ae1
"
2024/09/28 19:00:46,stdout,11:00:46: Request: GET /notes/0f90d38ca5c3425a84bbd5d2d771cfc5/tags?token=6676cf2c3fab2f7e6ebda5b7afcc0618e5111b9fa67abaa881f7d1448e3ec9986466d325cb26208d364a5a1cb67c90b59f4091fc0816dfc3e656d23298896ae1

2024/09/28 19:00:46,stdout,"11:00:46: Request: GET /notes/0f90d38ca5c3425a84bbd5d2d771cfc5?fields=body,title,is_todo,todo_completed&token=6676cf2c3fab2f7e6ebda5b7afcc0618e5111b9fa67abaa881f7d1448e3ec9986466d325cb26208d364a5a1cb67c90b59f4091fc0816dfc3e656d23298896ae1
"
2024/09/28 19:00:46,stdout,11:00:46: Request: GET /tags/1c4b41333e7441a5a154e0af04dffdb1/notes?token=6676cf2c3fab2f7e6ebda5b7afcc0618e5111b9fa67abaa881f7d1448e3ec9986466d325cb26208d364a5a1cb67c90b59f4091fc0816dfc3e656d23298896ae1

2024/09/28 19:00:46,stdout,11:00:46: Request: GET /tags?token=6676cf2c3fab2f7e6ebda5b7afcc0618e5111b9fa67abaa881f7d1448e3ec9986466d325cb26208d364a5a1cb67c90b59f4091fc0816dfc3e656d23298896ae1

2024/09/28 19:00:46,stdout,"11:00:46: Request: GET /notes?fields=id,title,parent_id,is_todo,todo_completed&token=6676cf2c3fab2f7e6ebda5b7afcc0618e5111b9fa67abaa881f7d1448e3ec9986466d325cb26208d364a5a1cb67c90b59f4091fc0816dfc3e656d23298896ae1
"
2024/09/28 19:00:46,stdout,11:00:46: Request: GET /folders?token=6676cf2c3fab2f7e6ebda5b7afcc0618e5111b9fa67abaa881f7d1448e3ec9986466d325cb26208d364a5a1cb67c90b59f4091fc0816dfc3e656d23298896ae1

2024/09/28 19:00:43,stdout,    stderr: 

2024/09/28 19:00:43,stdout,

**Comment by gri38** [comment]
thanks for reporting and for your investigation time.
Sorry for my bad reactivness...

I can reproduce. But... I really don't know how to fix.
I think it's a joplin data API bug... I've asked on discord... 

I let you know the progress here.

**Comment by gri38** [comment]
Waiting for a fix in joplin product.
